# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_cont_form_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_background = QtWidgets.QLabel(self.centralwidget)
        self.image_background.setGeometry(QtCore.QRect(-140, 0, 1061, 621))
        self.image_background.setStyleSheet("background-color: rgb(0, 0, 70);")
        self.image_background.setText("")
        self.image_background.setObjectName("image_background")
        self.user_name_account_s = QtWidgets.QLabel(self.centralwidget)
        self.user_name_account_s.setGeometry(QtCore.QRect(110, 10, 671, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.user_name_account_s.setFont(font)
        self.user_name_account_s.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 24pt \"Arial Black\";")
        self.user_name_account_s.setAlignment(QtCore.Qt.AlignCenter)
        self.user_name_account_s.setWordWrap(True)
        self.user_name_account_s.setObjectName("user_name_account_s")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(490, 150, 341, 260))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nume_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.nume_input.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.nume_input.setObjectName("nume_input")
        self.verticalLayout_2.addWidget(self.nume_input)
        self.prenume_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.prenume_input.setStyleSheet("\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.prenume_input.setObjectName("prenume_input")
        self.verticalLayout_2.addWidget(self.prenume_input)
        self.data_nasterii_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.data_nasterii_input.setStyleSheet("\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.data_nasterii_input.setObjectName("data_nasterii_input")
        self.verticalLayout_2.addWidget(self.data_nasterii_input)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(400, 110, 20, 341))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-93, 102, 1011, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(-50, 440, 1071, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 150, 271, 260))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nume_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nume_label.setFont(font)
        self.nume_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.nume_label.setObjectName("nume_label")
        self.verticalLayout.addWidget(self.nume_label)
        self.prenume_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.prenume_label.setFont(font)
        self.prenume_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.prenume_label.setObjectName("prenume_label")
        self.verticalLayout.addWidget(self.prenume_label)
        self.data_nasterii_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.data_nasterii_label.setFont(font)
        self.data_nasterii_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.data_nasterii_label.setObjectName("data_nasterii_label")
        self.verticalLayout.addWidget(self.data_nasterii_label)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(115, 495, 251, 61))
        self.save_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Arial\";\n"
"")
        self.save_button.setObjectName("save_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(485, 495, 251, 61))
        self.cancel_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Arial\";\n"
"")
        self.cancel_button.setObjectName("cancel_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_name_account_s.setText(_translate("MainWindow", "user_name_account"))
        self.nume_label.setText(_translate("MainWindow", "Nume"))
        self.prenume_label.setText(_translate("MainWindow", "Prenume"))
        self.data_nasterii_label.setText(_translate("MainWindow", "Data nașterii"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
