# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form_model.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit

from model.login_form_model.login import login_check
from views.user_form import UserForm


class LoginFormUi(object):
    def __init__(self, MainWindow_VAR):
        self.MainWindow_VAR = MainWindow_VAR

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(943, 606)
        self.login_titlu_label = QtWidgets.QLabel(Form)
        self.login_titlu_label.setGeometry(QtCore.QRect(370, 0, 241, 121))
        self.login_titlu_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                             "font: 87 50pt \"Arial Black\";")
        self.login_titlu_label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_titlu_label.setObjectName("login_titlu_label")
        self.login_button = QtWidgets.QPushButton(Form)
        self.login_button.setGeometry(QtCore.QRect(420, 370, 141, 61))
        self.login_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "font: 16pt \"Arial\";\n"
                                        "")
        self.login_button.setObjectName("login_button")
        self.parola_label = QtWidgets.QLabel(Form)
        self.parola_label.setGeometry(QtCore.QRect(210, 280, 121, 31))
        self.parola_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "font: 87 20pt \"Arial Black\";")
        self.parola_label.setAlignment(QtCore.Qt.AlignCenter)
        self.parola_label.setObjectName("parola_label")
        self.sign_up = QtWidgets.QLabel(Form)
        self.sign_up.setGeometry(QtCore.QRect(440, 470, 111, 31))
        self.sign_up.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 75 15pt \"MS Shell Dlg 2\";\n"
                                   "text-decoration: underline;")
        self.sign_up.setAlignment(QtCore.Qt.AlignCenter)
        self.sign_up.setObjectName("sign_up")
        self.password_input = QtWidgets.QLineEdit(Form)
        self.password_input.setGeometry(QtCore.QRect(210, 310, 571, 41))
        self.password_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                          "font: 12pt \"Arial\";")
        self.password_input.setObjectName("password_input")
        self.password_input.setEchoMode(QLineEdit.Password)
        self.username_input = QtWidgets.QLineEdit(Form)
        self.username_input.setGeometry(QtCore.QRect(210, 200, 571, 41))
        self.username_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                          "font: 12pt \"Arial\";")
        self.username_input.setObjectName("username_input")
        self.cant_access_account = QtWidgets.QLabel(Form)
        self.cant_access_account.setGeometry(QtCore.QRect(420, 530, 151, 21))
        self.cant_access_account.setStyleSheet("color: rgb(255, 255, 255);\n"
                                               "font: 87 14pt \"Arial Black\";\n"
                                               "font: 8pt \"MS Shell Dlg 2\";\n"
                                               "text-decoration: underline;")
        self.cant_access_account.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_access_account.setObjectName("cant_access_account")
        self.username_label = QtWidgets.QLabel(Form)
        self.username_label.setGeometry(QtCore.QRect(200, 150, 201, 51))
        self.username_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                          "font: 87 20pt \"Arial Black\";")
        self.username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.image_background = QtWidgets.QLabel(Form)
        self.image_background.setGeometry(QtCore.QRect(0, 0, 1061, 621))
        self.image_background.setText("")
        self.image_background.setPixmap(QtGui.QPixmap("C:/Users/cojoc/Downloads/Image1.png"))
        self.image_background.setObjectName("image_background")
        self.image_background.raise_()
        self.login_titlu_label.raise_()
        self.login_button.raise_()
        self.parola_label.raise_()
        self.sign_up.raise_()
        self.password_input.raise_()
        self.username_input.raise_()
        self.cant_access_account.raise_()
        self.username_label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        ######################

        self.login_button.clicked.connect(self.login_buttn_func)

    def login_buttn_func(self):
        if login_check(self.username_input.text(),
                       self.password_input.text()):
            self.run_user_form()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_titlu_label.setText(_translate("Form", "Login"))
        self.login_button.setText(_translate("Form", "Login"))
        self.parola_label.setText(_translate("Form", "Parola"))
        self.sign_up.setText(_translate("Form", "Sign Up !"))
        self.cant_access_account.setText(_translate("Form", "Can\'t acces your account?"))
        self.username_label.setText(_translate("Form", "Username"))

    def run_user_form(self):
        self.MainWindow_VAR.hide()
        self.FormWidget = QtWidgets.QMainWindow()
        self.ui = UserForm(self.username_input.text())
        try:
            self.ui.setupUi(self.FormWidget)
        except Exception as e:
            print(e)
        self.FormWidget.show()
        print('run user form')


def run():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = LoginFormUi(MainWindow)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


run()
