# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python Projects\VSCode\Chess\views\chess.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(996, 800)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.chess_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.chess_grid.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.chess_grid.setContentsMargins(0, 0, 0, 0)
        self.chess_grid.setObjectName("chess_grid")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(860, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(860, 300, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(870, 90, 47, 13))
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 390, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "reload"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.pushButton_3.setText(_translate("Form", "testtt"))
